src/Console/InstallCommand.php

Fixes the install command where, when installing Jetstream from the command, it would publish inertia assets when specifying the "livewire" stack.

fix command not publishing livewire assets

---

database/migrations/2014_10_12_000000_create_users_table.php
src/Console/InstallCommand.php
src/Contracts/CreatesConnectedAccounts.php
src/HasConnectedAccounts.php
src/Http/Controllers/OAuthController.php
src/Socialstream.php
stubs/app/Actions/Socialstream/CreateConnectedAccount.php
stubs/app/Actions/Socialstream/CreateUserFromProvider.php
stubs/app/Actions/Socialstream/CreateUserWithTeamsFromProvider.php
stubs/app/Providers/SocialstreamServiceProvider.php
tests/CreateUserFromProviderTest.php

This PR adds a new `current_connected_account_id` column to the users table. The value of this column is populated on registration & login with the id of the connected account used to start that session. 
A possible resolution to #9

[2.x] Current connected account context

---

stubs/inertia/resources/js/Socialstream/ActionLink.vue

The oauth provider ignores your oauth request with missing cors allowance. So you have to do a full-page request. Tested with github.

[1.x] fix CORS error by using anchor instead of inertia-link

---

src/HasConnectedAccounts.php

The getTokenFor method suggests that you will receive a token back, currently you are only querying for the token and not returning it.

[1.x] Fix token not being returned bug

---

src/Actions/GenerateRedirectForProvider.php
src/Contracts/GeneratesProviderRedirect.php
src/Http/Controllers/OAuthController.php
src/Socialstream.php
stubs/app/Providers/SocialstreamServiceProvider.php

This PR introduces an action that allows developers to specify an action used to generate provider redirect URI's. By default, the `JoelButcher\Socialstream\Actions\GenerateRedirectForProvider` action is used. 
As per #26, developers may need to specify scopes or additional parameters with the request:
```php
Socialite::driver($provider)
->scopes(['*'])
->with(['foo' => 'bar'])
->redirect()
```
This is now possible by extending the `GeneratesProviderRedirect` contract like so:
```php
<?php
namespace App\Actions;
use JoelButcher\Socialstream\Contracts\GeneratesProviderRedirect;
class CustomAction implements GeneratesProviderRedirect
{
/**
* Generates the redirect for a given provider.
* 
* @param  string  $provider
* 
* @return \Symfony\Component\HttpFoundation\RedirectResponse
*/
public …
```

[2.x] Added action for generating provider redirects

---

src/HasConnectedAccounts.php
stubs/app/Actions/Socialstream/CreateConnectedAccount.php
stubs/app/Actions/Socialstream/CreateUserFromProvider.php
stubs/app/Actions/Socialstream/CreateUserWithTeamsFromProvider.php
tests/CreateUserFromProviderTest.php

This PR injects the `CreatesConnectedAccounts` contract into `CreateUserFromProvider`. The goal is to reduce code duplication.

[1.x] Use action to create connected accounts.

---

database/migrations/2020_12_22_000000_create_connected_accounts_table.php
src/ConnectedAccount.php
src/Contracts/Credentials.php
src/Credentials.php
src/HasConnectedAccounts.php
src/Http/Controllers/OAuthController.php
stubs/app/Actions/Socialstream/CreateConnectedAccount.php
stubs/app/Actions/Socialstream/CreateUserFromProvider.php
stubs/app/Models/ConnectedAccount.php
tests/CreateUserFromProviderTest.php

This PR adds additional information from Socialite to the connected accounts table:
- Name,
- Nickname
- Email
- Avatar Path
This PR also introduces a new `Credentials` class which can be used for authenticating with a providers API's, if desired. Simply call the following code to retrieve an instance.
```php
$connectedAccount->getCredentials()
```
The credentials class adheres to `Arrayable`, `Jsonable` and `JsonSerializable` contracts, as well as the following contract
```php
<?php
namespace JoelButcher\Socialstream\Contracts;
use DateTimeInterface;
interface Credentials
{
/**
* Get the ID for the credentials.
*
* @return string
*/
public function getId();
/**
* Get token for the credentials.
*
* @return string
*/
public function getToken();
/**
* Get the token secret for the …
```

[2.x] Connected account details

---

src/ConnectedAccount.php
src/Http/Middleware/ShareInertiaData.php

This PR addresses several issues with #34. Most importantly, the overriding of `jsonSerialize`. I also moves the responsibility of this method to the abstract so that developers don't have to republish the ConnectedAccount model.
The key benefit of this change is the ability to customise and override the data shared to Inertia:
```php
/**
* Get the data that should be shared with Inertia.
*
* @return array
*/
public function getSharedInertiaData()
{
return [
//
]
}
```

[2.x] Move shared inertia data responsibility to ConnectedAccounts abstract

---

composer.json

Fix version conflict:  doctrine/dbal 3.0.0 with laravel nova 3.19.1 (doctrine/dbal 2.9)

Fix conflict doctrine/dbal

---

stubs/inertia/resources/js/Pages/Profile/ConnectedAccountsForm.vue

- Remove password focus since there is no password field to focus.
- Remove form .hasErrors() since this method do not exits on inertia form (probably existed on laravel-jetstream forms). Also there is no forms validation for this request.

Remove password focus & Fix error validation

---

src/ConnectedAccount.php
src/Http/Livewire/ConnectedAccountsForm.php
stubs/inertia/resources/js/Socialstream/ConnectedAccount.vue
stubs/livewire/resources/views/components/connected-account.blade.php

This pull request will change the "Connected on ..." format to the same as Jetstream Api Tokens last used ago.
It will changed the date format from 'd/m/Y H:i', since its not a unified format ~~and not customizable~~, to the diffForHumans() function.
Example: "6 minutes ago".

[2.x] Change connected date format to same as jetstream

---

src/ConnectedAccount.php
src/Http/Livewire/ConnectedAccountsForm.php

Adds a new `getSharedData` method to the Connected Account abstract class. This method defines the data exposed to Livewire / Inertia for use in the views.

[2.x] Define data shared method on model abstract.

---

config/socialstream.php
src/Http/Controllers/OAuthController.php

- This pull request will add a config option in order to th developer enable remember option to socialstream sessions.

[2.x] Add remember session option

---

config/socialstream.php
src/Features.php
src/Http/Controllers/OAuthController.php
src/Socialstream.php

This PR allows developers to choose whether or not user create an account from the login screen without having to go to `/register`.
This PR was inspired by #49, a great feature suggestion from @luiyongsheng. I was originally going to merge the branch in, but was conscious of adding another config item for developers to worry about. This PR resolves that worry by following the "features" pattern found in Laravel Jetstream and Fortify, becoming instantly familiar.
To enable the features simply add the following to your `socialstream.php` config file:
```php
'features' => [
\JoelButcher\Socialstream\Features::createAccountOnFirstLogin(),
]
```

[2.x] Feature: Create account on login

---

src/Http/Controllers/OAuthController.php

dangerBanner breaks due to the $provider_error key. Banner displays [object, object].
Recreate this issue by connecting an account to an already existing social account.
This :Provider sign in account is already associated with another user. Please try a different account.

[2.x] Fix danger banner [object, object] error

---

database/migrations/2020_12_22_000000_create_connected_accounts_table.php

Besides the `->foreignId('user_id')`, it seems like the table does not have built-in indexes for the following 2 queries:
```php
DB::table('connected_accounts')
->where('user_id', Auth::user()->getAuthIdentifier())
->where('id', $accountId)
->delete();
```
```php
static::newConnectedAccountModel()
->where('provider', $provider)
->where('provider_id', $providerId)
->first();
```

[3.x] Add indexes to the migration files

---

stubs/inertia/resources/js/Pages/Profile/ConnectedAccountsForm.vue

It seems like Jetstream moved on over `.native` in Vue 3: https://github.com/laravel/jetstream/pull/689/commits/5e3cf0c48418f19b5a74dbdadbdab62a8b47d52f

[3.x] Removed @click.native

---

stubs/inertia/resources/js/Pages/Profile/ConnectedAccountsForm.vue
stubs/livewire/resources/views/profile/connected-accounts-form.blade.php

- Do not show the button when the provider account is currently not connected. (Currently showing on Inertia Stack)
- Do not show the button if the profile photo is disabled on Jetstream.

[3.x] Show "Use Avatar as Profile Photo" button in the correct case

---

src/Features.php
src/Http/Controllers/OAuthController.php

This PR adds an additional feature to allow users to automatically login from the registration screen, if a user exists in the database for the email on the provider. If no associate connected account is found, one will be created linked to the resolved user.
resolves #115

[3.x] Allow users to auto-login on registration

---

src/Console/InstallCommand.php

This pull request removes the command to copy the ProviderIcons directory since the directory is alreay inside Socialstream folder.

[3.x] Remove ProviderIcons copy command

---

src/Http/Controllers/OAuthController.php

Fixed the  :
Getting **No such file or directory error after moving HandleInvalidState.php** to other location]
We used App\Actions\Socialstream\HandleInvalidState directly in the OAuthcontroller.php . So if we move to HandleInvalidState to other location. It will throw an error.
closes #127

[3.x] Use HandleInvalidState contract in OAuthController instead of hard-coded concrete

---

database/migrations/2020_12_22_000000_create_connected_accounts_table.php
src/SetsProfilePhotoFromUrl.php

Fix errors for images returned by OAuth2 that have too long of a URL. Every google account I tested with returns a URL over the max input for the column and what is supported by default with file_put_contents(). For reference, my GSuite account profile image URL returned was 821 characters long. To fix this I:
Increased the avatar_path length to 1000
Replaced the temporary filename with UUID

Fix profile photos that return long urls

---

src/HasConnectedAccounts.php

I was getting the following exception when getting connected accounts for users which were seeded and did not have any connected accounts:
_Error Trying to get property 'user_id' of non-object_ 
I've included a conditional to check whether there is a connected account which fixes this for me.

[FIX] - Add conditional on empty connected account

---

stubs/inertia/resources/js/Socialstream/Providers.vue
stubs/livewire/resources/views/components/socialstream-providers.blade.php

Writes GitHub with capital letters for the H

[3.x] Fix GitHub nomenclature

---

stubs/inertia/resources/js/Pages/Profile/Show.vue

Noticed a missing title on the Inertia Profile Show component, which is present in Laravel Jetstream with it's initial Inertia scaffolding.

[3.x] Fix missing title on AppLayout component

---

src/SetsProfilePhotoFromUrl.php

While using a avatar on my windows dev machine, I faced this issue 
I've simply replaced '/tmp/' with php's `sys_get_temp_dir`-function, IMHO the correct way to set the tmp path 😄

fix file_put_contents bug on windows

---

src/Http/Controllers/OAuthController.php

When user A registers and connects a social account, then updates his user email, they can register a new user account using the same social account.
The result is 2 users that has the same social account connected. 
When trying to login with that social account, it will login the first user (first connected account returned from the query)
By checking if there is no account found, and only then enter the registration block we can prevent that, and skip to login the correct user.

[3.x] Prevent multiple users connect the same social account 

---

src/Providers.php
tests/ProvidersTest.php

Partially resolves problems highlighted in #168. This PR adds some nice syntactic sugar on top of the `Providers` class.
Developer registering new providers (that don't come supported out-of-the-box), can now easily call check if their provider is enabled using a new `Providers::hasMyCustomProviderSupport` syntax.
Consider the following example:
```php
return [
'providers' => [
Providers::github(),
Providers::facebook(),
'apple' // Apple is not supported as a provider by Laravel Socialite and thus, not supported out-of-the-box by Socialstream
],
];
```
You now wish to update `socialstream-providers.blade.php` to cater for your condition. You can now call `Providers::hasAppleSupport()` to determine if the `apple` provider has been registered:
```blade
@if …
```

[3.x] Add dynamic method calls for custom providers

---

src/Contracts/ResolvesSocialiteUsers.php
stubs/app/Actions/Socialstream/ResolveSocialiteUser.php

This pull request improves the @return value from src/Contracts/ResolvesSocialiteUsers.php.
Currently the @return value for the following code is `Laravel\Socialite\Contracts\User`:
```php
$user = Socialite::driver($provider)->user();
```
This return type is less specific than the return type of the `resolve` from socialstream `Laravel\Socialite\AbstractUser`.
Throwing some warnings on static analysis such as Psalm (https://psalm.dev/129). This pull request do not impact in the code itself.

Simple DocBlock improvement

---

src/Http/Controllers/Inertia/RemoveConnectedAccountsController.php

I recently discovered that removing an OAuth provider using the Redis session driver did not work. Going through the code I saw that only the database session driver is allowed to delete connected accounts.
I do not see a reason for this, so I am creating a PR to remove this check. If I am incorrect and there is a reason for this that I am not thinking of, is there a future plan to support deleting connected accounts using other drivers?

Fix account removal for non-databse sessions

---

src/Http/Controllers/OAuthController.php

Discussion: https://github.com/joelbutcher/socialstream/discussions/189
example Inertia props:
current
```json
{
"errorBags": {
"default": [
[
"An account with that email address already exists. Please login to connect your Github account."
]
]
},
"errors": {
"0": "An account with that email address already exists. Please login to connect your Github account."
}
}
```
before https://github.com/joelbutcher/socialstream/pull/172
```json
{
"errorBags": {
"socialstream": [
[
"An account with that email address already exists. Please login to connect your Github account."
]
]
},
"errors": {
"socialstream": {
"0": "An account with that email address already exists. Please login to connect your Github account."
}
}
}
```
after
```json
{
"errorBags": {
"default": {
"socialstream": [
"An account …
```

fix: put OAuth errors into MessageBag

---

src/Http/Controllers/Inertia/UpdateUserProfilePhotoController.php

If you make a PUT request to ```/user/profile-photo```, an ```ErrorException``` will be thrown if there is no account returned, which can happen if ``` $request->id``` is not provided or does not exist.
```
ErrorException: Attempt to read property "avatar_path" on null in file /var/www/html/vendor/joelbutcher/socialstream/src/Http/Controllers/Inertia/UpdateUserProfilePhotoController.php on line 23
```
Changing "! is_null()" to "isset()" will ensure that the variable exists and is not null.

Fix 'Attempt to read property "avatar_path" on null' error on "Use Avatar as Profile Photo" action

---

src/Console/InstallCommand.php

This PR uses Symfony's `Process` mechanics to install node dependencies and build the frontend for users automatically, once Socialstream has been installed.

[3.x] auto-install node and build frontend

---

.github/workflows/tests.yml
composer.json

This PR updates Socialstream to drop support for Laravel 8.x and by extension, drop support for PHP 7.3 & 7.4.
Although the change is made in the repo, because Jetstream is a dependency and has already drop support for Laravel 8, up until now, this will have been reflected via composer's dependency management.

[3.x] Drop Laravel 8.x and PHP 7.3, 7.4 

---

stubs/inertia/resources/js/Socialstream/ConnectedAccount.vue
stubs/inertia/resources/js/Socialstream/Providers.vue
stubs/livewire/resources/views/components/connected-account.blade.php
stubs/livewire/resources/views/components/socialstream-providers.blade.php

Fixes following bugs with new Twitter oAuth2:
- Twitter Icon doesn't show in ConnectedAccount.vue if oAuth2
- Provider name now shows as 'Twitter' instead of "Twitter-oauth2" in ConnectedAccounts List
- Twitter oauth2 now links to the correct endpoint in Providers.vue
All changes apply for vue and livewire.

[3.x] Fix Twitter OAuth 2.0 redeirect URL generation links

---

stubs/inertia/resources/js/Components/ConnectedAccount.vue

This PR fixes an issue introduced by #208 whereby the twitter icon is shown next to the icon of any enabled provider in the `ConnectedAccount.vue` component:

[3.x] Fix twitter icon bug in enabled providers in connected account form

---

README.md

This PR updates the `README.md` document to point developers to the [new documentation site](https://docs.socialstream.dev) in Gitbooks

[3.x] Update readme documentation

---

src/Http/Controllers/OAuthController.php

Currently you can enable automatic new-user registration via the login flow, and you can enable linking an existing user to a new connected account via the registration flow, but you can't link an existing user to a new connected account via the login flow - this PR adds that if you are using `hasCreateAccountOnFirstLoginFeatures`.

[3.x] Support linking connected accounts via the login flow

---

src/ConnectedAccount.php
src/HasConnectedAccounts.php

The `authIdentifier` is used to retrieve connected accounts, which will cause an error if the `authIdentifier` has been changed, to for instance something like `uuid`. 
```php   
/**
* Set the providers avatar url as the users profile photo url.
*
* @param  mixed  $accountId
*/
public function setAvatarAsProfilePhoto($accountId)
{
$account = Auth::user()->connectedAccounts
->where('user_id', ($user = Auth::user())->getAuthIdentifier())
->where('id', $accountId)
->first();
if (is_callable([$user, 'setProfilePhotoFromUrl']) && ! is_null($account->avatar_path)) {
$user->setProfilePhotoFromUrl($account->avatar_path);
}
return redirect()->route('profile.show');
}
```
This PR avoids users of the package having to override relationship methods if they change the `authIdentifier`. 
Migrations are …

Use `authIdentifier` in relationships

---

stubs/inertia/resources/js/Pages/Profile/ConnectedAccountsForm.vue

When installing the latest update with Ineria v1 and Vue3 you get the following error when loading the profile page in Jetstream.
This PR makes the inertiaProps inside of the **ConnectedAccountsForm.vue** form to have computed data so that the values will show under **inertiaProps.value**.

Adding computed inertiaProps to fix console errors

---

src/Actions/Auth/AuthenticateOauthCallback.php
src/Actions/Auth/HandleOauthCallbackErrors.php
src/Contracts/AuthenticatesOauthCallback.php
src/Contracts/HandlesOauthCallbackErrors.php
src/Http/Controllers/OAuthController.php
src/Socialstream.php
src/SocialstreamServiceProvider.php

This PR
- moves the logic used for handling request errors on return back from an OAuth flow to an action
- moves the authentication logic used for creating and authenticating users returning from an OAuth flow into an action
- Allows developers to override both of these via overriding the `authenticatesOauthCallbackUsing` and `handlesOAuthCallbackErrorsUsing` bindings:
```php
Socialstream::authenticatesOauthCallbackUsing(AuthenticateOauthCallback::class);
Socialstream::handlesOAuthCallbackErrorsUsing(HandleOauthCallbackErrors::class);
```

[4.x] Allow customisation of authentication logic

---

src/Http/Middleware/ShareInertiaData.php

All of the responses are coming from Symfony HttpFoundation Response object, so optimise it to use it. Also avoids some issues in using Laravel Spark when downloading Stripe receipt.

[4.x] Use base Symfony response class as return type for `ShareInertiaData`

---

stubs/livewire/resources/views/components/connected-account.blade.php

This pull request is a tiny fix to add the use of default Laravel translation files for the word 'Connected'. 
- [ x] I've read this template
- [ x] I've checked reviewed this PR myself, ensuring consistency and quality with the rest of the project
- [ x] I've given a good reason as to why this PR exposes new / removes existing user data

[4.x] use translation for "Connected :at"

---

composer.json
src/Providers.php
src/Resolvers/OAuth/LinkedInOpenIdOauth2RefreshResolver.php
src/Socialstream.php
src/SocialstreamServiceProvider.php
stubs/inertia/resources/js/Components/ConnectedAccount.vue
stubs/inertia/resources/js/Components/Socialstream.vue
stubs/livewire/resources/views/components/connected-account.blade.php
stubs/livewire/resources/views/components/socialstream.blade.php
stubs/pest-tests/SocialstreamRegistrationTest.php
stubs/tests/SocialstreamRegistrationTest.php
tests/Unit/ProvidersTest.php

This pull request add's a new provider to support LinkedIn's OpenID authentication mechanics.
resolves #284

[4.x] Added LinkedIn OpenID Support

---

src/Console/InstallCommand.php
src/Installer/Drivers/Filament/FilamentDriver.php
stubs/filament/pest-tests/SocialstreamRegistrationTest.php
stubs/filament/tests/SocialstreamRegistrationTest.php

This PR:
- Prompts users to select their test runner when installing for Filament Admin Panel
- Publishes PHPUnit or Pest feature tests for Filament Admin Panel
- Prompts the user to select a starter kit if there is a clash of multiple starter kits (e.g. Filament **AND** Laravel Breeze are installed)

[5.x] Publish tests for Filament

---

.styleci.yml

Removes the `.styleci.yml` config file from VSC for 5.x as coding standards have moved over to Laravel Pint

[5.x] Remove StyleCI

---

.github/workflows/fix-code-styling.yml
.styleci.yml

Updates 2.x to use Laravel Pint instead of StyleCI

[2.x] Use Laravel Pint 🍺

---

.github/workflows/fix-code-styling.yml
.styleci.yml

Updates 4.x to use Laravel Pint instead of StyleCI

[4.x] Use Laravel Pint 🍺

---

.github/workflows/fix-code-styling.yml
.styleci.yml

Updates 3.x to use Laravel Pint instead of StyleCI

[3.x] Use Laravel Pint 🍺

---

stubs/jetstream/livewire/resources/views/components/validation-errors.blade.php

[5.x] Fix call to undefined method `except` on `$errors`

---

src/Actions/AuthenticateOAuthCallback.php
src/Actions/HandleOAuthCallbackErrors.php

Resolves the routes to redirect already authenticated users to when using Filament

[5.x] Fix undefined routes for authenticated users in Filament

---

src/Actions/AuthenticateOAuthCallback.php

Fix OAuth callback error message
The OAuth callback error was not displaying the provider name in the message.
when using a config like this, without Label:
```php
return [
'middleware' => ['web'],
'prompt' => 'Or Login Via',
'providers' => [
Providers::github(),
],
];
```

[5.x] Use provider names in error messages

---

stubs/breeze/inertia-react-ts/resources/js/Pages/Profile/Partials/ConnectedAccountsForm.tsx
stubs/breeze/inertia-react/resources/js/Pages/Profile/Partials/ConnectedAccountsForm.jsx
stubs/breeze/inertia-vue-ts/resources/js/Components/ConnectedAccount.vue
stubs/breeze/inertia-vue-ts/resources/js/Pages/Profile/Partials/ConnectedAccountsForm.vue
stubs/breeze/inertia-vue/resources/js/Components/ConnectedAccount.vue
stubs/breeze/inertia-vue/resources/js/Pages/Profile/Partials/ConnectedAccountsForm.vue
stubs/breeze/livewire-functional/resources/views/livewire/profile/connected-accounts-form.blade.php
stubs/breeze/livewire/resources/views/livewire/profile/connected-accounts-form.blade.php
stubs/jetstream/inertia/resources/js/Components/ConnectedAccount.vue
stubs/jetstream/inertia/resources/js/Pages/Profile/Partials/ConnectedAccountsForm.vue
stubs/jetstream/livewire/resources/views/profile/connected-accounts-form.blade.php

Replaces the existing copy of the connected accounts form with less, more concise text. Also moves the warning to above the list of connected accounts, and styles it to stick out more:

[5.x] Update design and copy for connected accounts form

---

routes/socialstream-inertia.php
routes/socialstream.php
src/Actions/AuthenticateOAuthCallback.php
src/ConnectedAccount.php
src/Policies/ConnectedAccountPolicy.php
src/SocialstreamServiceProvider.php
tests/Feature/RouteCachingTest.php
tests/Feature/SocialstreamTest.php
tests/TestCase.php
workbench/routes/web.php

Uses `Route::match(…)` to resolve the OAuth callback for both GET and POST HTTP verbs in order to cache the route for both methods with the same name.
Addresses issues identified in #288

[5.x] fix: duplicate route names

---

.github/workflows/check-pr-maintainer-access.yml
.github/workflows/manage-issue.yml

Adds new maintainer GitHub actions that:
1. Closes a issue if there is no reproduction repository
2. Closes an issue if maintainer edit access has not been granted

[5.x] New maintainer GH actions

---

src/Actions/AuthenticateOAuthCallback.php
tests/Feature/CreateAccountOnFirstLoginTest.php
tests/Feature/LoginOnRegistrationTest.php

The refactoring from https://github.com/joelbutcher/socialstream/pull/325 flushed the OAuth logic again, making it very hard to understand how the authentication flow works. On top of that, it introduced a vulnerability/bug where the user can link a provider account to an existing account without the `loginOnRegistration()` feature enabled.
To reproduce, the system must have `Features::globalLogin()` and `Features::createAccountOnFirstLogin()` enabled, and the user needs to authenticate using a non-linked provider from a random route.
The first point I observed is that Oauth is using multiple points to create an account (or provider account) again. You can see that `$this->createsConnectedAccounts->create()` is used three times and `$this->register()` two times, opening gaps for problems …

[5.x] Fix user being able to link account without loginOnRegistration()

---

stubs/jetstream/livewire/resources/views/profile/connected-accounts-form.blade.php

At line 71, of the `connected-accounts-form.blade.php`
The value : 
`"$toggle('confirmingRemove')"` 
does not seems to exist anymore, it should be remove by : 
`"$toggle('confirmingAccountRemoval')"`
```
<x-slot name="footer">
<x-secondary-button wire:click="$toggle('confirmingRemove')" wire:loading.attr="disabled">
{{ __('Cancel') }}
</x-secondary-button>
<x-danger-button class="ml-2" wire:click="removeConnectedAccount" wire:loading.attr="disabled">
{{ __('Remove Account') }}
</x-danger-button>
</x-slot>
```
Should be : 
```
<x-slot name="footer">
<x-secondary-button wire:click="$toggle('confirmingAccountRemoval')" wire:loading.attr="disabled">
{{ __('Cancel') }}
</x-secondary-button>
<x-danger-button class="ml-2" wire:click="removeConnectedAccount" wire:loading.attr="disabled">
{{ …
```

[5.x] Fix removed cancel modal toggle action

---

src/Contracts/HandlesInvalidState.php

In certain cases, it would be great if the HandlesInvalidState class could also return a RedirectResponse object.
Much simpler when you want to redirect in case of error Invalid State exception
@joelbutcher

[5.x]: Allow HandlesInvalidState to return an instance of RedirectResponse

---

composer.json
src/Data/ProviderData.php

This pull request removes the `webmozart/assert` package. The package is used in only one file to throw `InvalidArgumentException` in some scenarios.  Although these exceptions are never caught, the PR manually adds the exceptions with the exact same messages from the package. 
The motivation for this PR is because the package is giving some strange conflict errors when trying to install `vimeo/psalm` with `socialstream` and `webmozart/asset` with an already composer.lock generated.
Manually adding `vimeo/psalm` to the project and deleting the composer.lock fixes the conflict. However, since this package's last commit was **2 years ago** and is only being used in one single file, I personally don't see a reason to keep it.

[6.x] Remove webmozart/assert package

---

stubs/breeze/livewire-functional/resources/views/livewire/profile/set-password-form.blade.php

Syntax error: unexpected token Fixx

[6.x] Fix syntax error in breeze livewire-functional set-password-form

---

.github/workflows/breeze-stub-tests.yml
composer.json
src/Installer/Drivers/Jetstream/JetstreamDriver.php

Fixes the following error:
```bash
ErrorException
copy(/Users/joel/Projects/blog/resources/js/Pages/Profile/Partials/ConnectedAccountsForm.vue): Failed to open stream: No such file or directory
at /Users/joel/Projects/socialstream/src/Installer/Drivers/Jetstream/InertiaDriver.php:48
44▕      * Copy the profile views to the app "resources" directory for the given stack.
45▕      */
46▕     public function copyProfileViews(InstallOptions ...$options): static
47▕     {
➜  48▕         copy(__DIR__.'/../../../../stubs/jetstream/inertia/resources/js/Pages/Profile/Partials/ConnectedAccountsForm.vue', resource_path('js/Pages/Profile/Partials/ConnectedAccountsForm.vue'));
49▕         copy(__DIR__.'/../../../../stubs/jetstream/inertia/resources/js/Pages/Profile/Partials/SetPasswordForm.vue', …
```

[6.x] - [fix] install command not installing Laravel Jetstream and failing

---

src/Actions/AuthenticateOAuthCallback.php
src/Actions/RedirectIfTwoFactorAuthenticatable.php
src/Concerns/ConfirmsFilament.php
src/Http/Responses/OAuthFailedResponse.php

Fixes a bug introduced in #351 and #361

[6x] Fix auth for users with changed emails

---

src/Auth/SocialstreamUserProvider.php
src/SocialstreamServiceProvider.php

Resolves #366 
The problem is that when ever anyone has "registered" with a provider, the `users.password` field is set to `NULL` in the database. Therefore attempting to authenticate a user with their email and password throws an error exception, presenting itself as a 500 server error.
The default eloquent user provider (rightly) assumes that the `user.password` column is always filled with a password hash (as is the default behaviour of every Laravel app). This results in the underlying hasher checking a hashed password from the form against `NULL`, which throws the error.
The fix here is to override the `eloquent` user provider with our own user provider. This provider only `extends` the base one and only overrides the methods that matter (in this case only the `validateCredentials` …

[6.x] – Override default `EloquentUserProvider` to check $user->authPassword before checking hashes match

---

src/Actions/AttemptToAuthenticate.php
src/Actions/AuthenticateOAuthCallback.php
stubs/app/Providers/SocialstreamServiceProvider.php

Fixes a bug where, when using `Fortify::authenticateThrough` in a service provider, the auth for Socialstream fails and kicks users out of the application (e.g. to the My Account page for Google OAuth).
The problem is fixed by iterating over the pipes used by Fortify (or in the custom callback) and replacing Fortify's instances of `AttemptToAuthenticate` and `RedirectIfTwoFactorAuthenticatable` with our own.
Resolves #378 
> [!Note]
> This does not solve the problem where developers create their own custom authentication implementations and don't use fortify's at all

[6.x] fix auth when using a custom authentication pipeline in Fortify

---

src/Http/Controllers/Inertia/ConnectedAccountController.php

Directly deleting the database entry prevents the deletion model event from firing.
Resolves #382
This pull request retrieves the relevant model prior to issuing the deletion so as to trigger the deletion model event.

[6.x] retrieve the model to allow deletion to fire model events

---

composer.json
src/Http/Controllers/OAuthController.php
src/Socialstream.php
stubs/breeze/inertia/app/Http/Controllers/ProfileController.php

This PR allows developers to override how a user is prompted to confirm a connection with an OAuth provider when they are logged in.
Simply pass a closure to `Socialstream::promptOAuthLinkUsing(...)` that returns either `view(...)` or `Inertia::render(...)` inside the `boot` method of your `AppServiceProvider`:
```php
public function boot(): void
{
Socialstream::promptOAuthLinkUsing(
fn (string $provider) => view('pages.auth.oauth.confirm-link-provider', ['provider' => $provider])
);
}
```
```php
public function boot(): void
{
Socialstream::promptOAuthLinkUsing(
fn (string $provider) => Inertia::render('Auth/OAuth/ConfirmLinkProvider', ['provider' => $provider])
);
}
```

[6.x] Allow custom OAuth prompts
