src/Http/Controllers/OAuthController.php, stubs/inertia/resources/js/Pages/Profile/ConnectedAccountsForm.vue, stubs/inertia/resources/js/Socialstream/ConnectedAccount.vue, stubs/livewire/resources/views/components/connected-account.blade.php, stubs/livewire/resources/views/profile/connected-accounts-form.blade.php
Fixes the `connected-accounts` issues raised in #3 where and adds an error message for connected accounts on the profile page
=> Tidy connected accounts

src/Console/InstallCommand.php, src/Contracts/HandlesInvalidState.php, src/Http/Controllers/OAuthController.php, src/Socialstream.php, stubs/app/Actions/Socialstream/HandleInvalidState.php, stubs/app/Providers/SocialstreamServiceProvider.php
This PR adds and publishes a new action to handle `Laravel\Socialite\Two\InvalidStateException` (#3 )
=> [1.x] Handle invalid state exceptions

src/Console/InstallCommand.php, stubs/app/Actions/Jetstream/DeleteUser.php, stubs/app/Actions/Jetstream/DeleteUserWithTeams.php
=> [1.x] Delete connected accounts on user deletion

stubs/inertia/resources/js/Pages/Profile/Show.vue
Fix visibility check on the delete user button
=> [1.x] Fix delete account form showing if password isn't set

src/Http/Middleware/ShareInertiaData.php
Detect whether there is a logged-in user profile to fetch data from.
=> [1.x] Ensure user exists in ShareInertiaData

src/Http/Middleware/ShareInertiaData.php
Return empty array in guest mode.
=> [1.x] fix connected accounts inertia prop

stubs/inertia/resources/js/Socialstream/ActionLink.vue
removed garbage chars at the end of the file
=> [1.x] fix formatting

stubs/inertia/resources/js/Pages/Profile/ConnectedAccountsForm.vue
This PR removes duplicate method getAccountForProvider in inertia stack.
=> [1.x] remove duplicate method getAccountForProvider

src/Console/InstallCommand.php, stubs/inertia/resources/js/Pages/Auth/Login.vue, stubs/inertia/resources/js/Pages/Auth/Register.vue, stubs/inertia/resources/js/Pages/Profile/ConnectedAccountsForm.vue, stubs/inertia/resources/js/Pages/Profile/SetPasswordForm.vue, stubs/inertia/resources/js/Pages/Profile/Show.vue, stubs/inertia/resources/js/Socialstream/Providers.vue
Fixes several issues with the publishing of the inertia stack, including #31
=> [2.x] Fix inertia

config/socialstream.php
- This pull request will just change the .env parameter from `SHOW_SOCIALSTREAM` to `SOCIALSTREAM_SHOW`. I think this will not introduce any break change, since the configuration file would not be changed in already published projects.
=> [3.x] Change .env parameter format

config/socialstream.php, src/Features.php, src/Http/Controllers/OAuthController.php, src/Socialstream.php
This PR takes the remember session config option added in #44 to the packages feature flags.
=> Add remember session to feature flags

README.md
Config and setup info in Readme (taken from medium guide), as I had to hunt through the closed issues to find this information.
=> [2.x] Add configuration steps to README

stubs/app/Actions/Socialstream/CreateUserFromProvider.php
https://github.com/joelbutcher/socialstream/issues/13
=> if name empty, use nickname

src/Http/Controllers/OAuthController.php
As mentioned in #90 , I wanted to add Named Error Bags :)
It should work like this, please format it as you want :)
=> [2.x] Use Named Error Bags

src/Console/InstallCommand.php
=> [3.x] Publish missing stub

stubs/livewire/resources/views/profile/show.blade.php
https://github.com/joelbutcher/socialstream/pull/107
=> Add missing jetstream feature flag

src/Http/Controllers/OAuthController.php
=> [3.x] use fortify login response contract

src/Http/Controllers/OAuthController.php
There were some weird scenarios like this:
=> [3.x] Fixed banners looking like arrays

config/socialstream.php
This pull request adds all features to the configuration file that is published at installation time in order to show whoever is using the package for the first time what are the available features.
When I tried to find, I couldn't find it in the documentation and the only way I could find out was using the IDE to browse the package and checking available features on it code.
=> [3.x] Add all available features to config file

src/Http/Controllers/OAuthController.php
Completed the fix for issue #115 
Plus found another issue with the call to alreadyAuthenticated() where the parameter order was not correct.
=> [3.x] Fix incorrect OAuthController method calls

database/migrations/2020_12_22_000000_create_connected_accounts_table.php
=> [3.x] update avatar_path causing errors when using Google as OAuth

README.md
=> [3.x] Add features to README

src/Http/Controllers/OAuthController.php
=> [3.x] Check registration feature is enabled when handling errors

src/Console/InstallCommand.php
This PR updates the output of the `socialstream:install` artisan command to use the new Termwind components included in Laravel
=> [3.x] Use Termwind

src/Console/InstallCommand.php, src/Providers.php, src/Socialstream.php, stubs/inertia/resources/js/Socialstream/Providers.vue, stubs/pest-tests/SocialstreamRegistrationTest.php, stubs/tests/SocialstreamRegistrationTest.php, tests/ProvidersTest.php
This PR adds a new provider for the `twitter-oauth-2`.
=> [3.x] Add support for Twitter OAuth 2 Provider

src/SetsProfilePhotoFromUrl.php
Fixes issue when allow_url_fopen is disabled
=> [3.x] Use Http Client to fetch photo from URL

stubs/inertia/resources/js/Pages/Auth/Login.vue, stubs/inertia/resources/js/Pages/Auth/Register.vue, stubs/inertia/resources/js/Pages/Profile/SetPasswordForm.vue
=> [3.x] Fix label component imports

stubs/livewire/resources/views/profile/connected-accounts-form.blade.php
Minor change to correct a typo in the connected accounts description.
=> [3.x] Update connected accounts description

stubs/app/Policies/ConnectedAccountPolicy.php, stubs/app/Providers/AuthServiceProvider.php, stubs/app/Providers/SocialstreamServiceProvider.php, stubs/app/Providers/TeamsAuthServiceProvider.php
Updates files that were missed when updating type declarations
=> [4.x] Update missing type declarations

UPGRADE.md, stubs/app/Policies/ConnectedAccountPolicy.php, stubs/app/Providers/AuthServiceProvider.php, stubs/app/Providers/SocialstreamServiceProvider.php, stubs/app/Providers/TeamsAuthServiceProvider.php
Updates the `UPGRADE.md` readme file with changes for type declarations
=> [4.x] Update upgrade

UPGRADE.md, src/Console/InstallCommand.php, stubs/app/Actions/Socialstream/GenerateRedirectForProvider.php, stubs/app/Providers/SocialstreamServiceProvider.php
=> [4.x] Fix unpublishable provider redirect action

src/Console/InstallCommand.php
=> [4.x] Publish `GenerateRedirectForProvider` action when installing the inertia stack

src/Console/InstallCommand.php, stubs/inertia/resources/js/Components/ConnectedAccount.vue, stubs/inertia/resources/js/Components/Socialstream.vue, stubs/inertia/resources/js/Pages/Auth/Login.vue, stubs/inertia/resources/js/Pages/Auth/Register.vue, stubs/inertia/resources/js/Pages/Profile/ConnectedAccountsForm.vue, stubs/livewire/resources/views/auth/login.blade.php, stubs/livewire/resources/views/auth/register.blade.php, stubs/livewire/resources/views/components/connected-account.blade.php, stubs/livewire/resources/views/components/socialstream.blade.php, stubs/livewire/resources/views/profile/connected-accounts-form.blade.php
This pull request updates Socialstream's components and overrides to support Jetstream's Dark Mode feature, removing dark mode classes they are not required by the developer.
=> [3.x] Dark mode support

src/Http/Livewire/SetPasswordForm.php
=> replace emit to dispatch

stubs/inertia/resources/js/Components/ConnectedAccount.vue
=> [4.x] Fix ConnectedAccount.vue component

stubs/breeze/database/factories/UserFactory.php, stubs/filament/database/factories/UserFactory.php, stubs/jetstream/database/factories/UserFactory.php
Updates the `UserFactory` classes to use the new `fake()->thing` syntaxt
=> [5.x] Fix User Factories

resources/filament/views/components/socialstream.blade.php
Fixes the default dark mode styling for filament
=> [5.x] Update default dark mode styling for filament

src/Filament/SocialstreamPlugin.php
Fixes the following error in the filament stack:
=> [5.x] Fix filament error bag

composer.json, src/Installer/Drivers/Breeze/BreezeDriver.php, stubs/breeze/livewire-functional/resources/views/livewire/pages/auth/login.blade.php, stubs/breeze/livewire-functional/resources/views/livewire/pages/auth/register.blade.php, stubs/breeze/livewire-functional/resources/views/livewire/profile/connected-accounts-form.blade.php, stubs/breeze/livewire-functional/resources/views/livewire/profile/delete-user-form.blade.php, stubs/breeze/livewire-functional/resources/views/livewire/profile/set-password-form.blade.php, stubs/breeze/livewire/resources/views/livewire/pages/auth/login.blade.php, stubs/breeze/livewire/resources/views/livewire/pages/auth/register.blade.php, stubs/breeze/livewire/resources/views/livewire/profile/connected-accounts-form.blade.php, stubs/breeze/livewire/resources/views/livewire/profile/delete-user-form.blade.php, stubs/breeze/livewire/resources/views/livewire/profile/set-password-form.blade.php
Aligns the Breeze Livewire stacks with change made in laravel/breeze#326. Also ensures Laravel Breeze ^1.26 is installed when using any Breeze stack
=> [5.x] Align breeze livewire stacks

composer.json
=> [6.x] Remove dbal composer requirements

src/Http/Responses/OAuthProviderLinkFailedResponse.php, tests/Feature/SocialstreamTest.php
=> [5.x] Bugfix redirect on OAuth Link Failed

src/Installer/Drivers/Driver.php
=> [6.x] Publish service provider

src/Http/Responses/OAuthLoginResponse.php, src/Http/Responses/OAuthRegisterResponse.php, src/Socialstream.php
=> [6.x] fix auth redirects

.gitattributes, resources/views/oauth/test-prompt.blade.php, src/Http/Controllers/OAuthController.php, src/Socialstream.php, tests/Feature/SocialstreamTest.php
=> [6.x] fix: custom oauth prompt callback registration
